config/routes.rb
Jade::Application.routes.draw do
  root :to => 'welcome#index'

  get "welcome/index"

  resources :campaigns
 
  resources :after_register

  devise_for :clients, :controllers => { :registrations => "registrations" }
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  attr_accessible :name, :period
  belongs_to :client

  validates :name, :presence => true

  def period
  end

  def period=(period)
    dates = period.split(" - ")
    self.start_date = dates[0]
    self.end_date = dates[1]
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name

  has_many :campaigns
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/after_register_controller.rb
class AfterRegisterController < Wicked::WizardController
  before_filter :authenticate_client!

  steps :add_name

  def show
    @client = current_client
    render_wizard
  end

  def update
    @client = current_client
    @client.update_attributes(params[:client])
    render_wizard @client
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/campaigns_controller.rb
include ApplicationHelper

class CampaignsController < ApplicationController
  before_filter :authenticate!
  before_filter :authenticate_client!, :except => [:index, :show]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campaigns }
    end
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/new
  # GET /campaigns/new.json
  def new
    @campaign = Campaign.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/1/edit
  def edit
    @campaign = Campaign.find(params[:id])
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(params[:campaign])

    @campaign.client = current_client

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render json: @campaign, status: :created, location: @campaign }
      else
        format.html { render action: "new" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /campaigns/1
  # PUT /campaigns/1.json
  def update
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      if @campaign.update_attributes(params[:campaign])
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    super
  end

  protected
    def after_sign_up_path_for(resource)
      after_register_path(:add_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  protect_from_forgery
  def index
    if user_signed_in? 
      redirect_to campaigns_path
    elsif client_signed_in?
      redirect_to campaigns_path
    end
  end
end

app/helpers/after_register_helper.rb
module AfterRegisterHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def authenticate!
    if not (user_signed_in? || client_signed_in?)
      redirect_to root_path
    end
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/after_register/add_name.html.erb
<div class="page-header">
  <h1>Next Step</h1>
</div>

<div style='padding-bottom:15px'>
  <h4>추가 정보를 입력해주세요.</h4>
</div>

<%= simple_form_for(@client, :url => wizard_path, :method => :put, :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.input :name, :label => '회사명' %>
  <%= f.submit 'Next', :class => 'btn btn-primary' %>
<% end %>

app/views/campaigns/_form.html.erb
<%= simple_form_for @campaign, :html => { :class => 'form-horizontal' } do |f| %>
  <div class='control-group'>
    <%= f.input :name, label: '캠페인 제목:' %>
  </div>
  <div class='control-group'>
    <%= f.button :submit %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), campaigns_path, :class => 'btn' %>
  </div>
<% end %>

app/views/campaigns/_new_form.html.erb
<%= simple_form_for @campaign, :html => { :class => 'form-horizontal' } do |f| %>
<!-- Calendar -->
  <fieldset>
    <div class="control-group">
      <%= f.input :period, label: '기간:', input_html: { id: 'campaign_period', value: eval("String(Time.now).split[0] + ' - ' + String(Time.at(Time.now + 60*60*24*7)).split[0]") } %>
    </div>
    <div class="control-group">
      <%= f.input :name, label: '캠페인 제목:' %>
    </div>
    <div class='control-group'>
      <%= f.button :submit %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")), campaigns_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/campaigns/edit.html.erb
<%- model_class = Campaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/campaigns/index.html.erb
<%- model_class = Campaign -%>

<div class="page-header">
  <h1>캠페인</h1>
</div>

<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("mainBanner_img_131.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("mainBanner_img_132.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("mainBanner_img_133.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("mainBanner_img_134.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("mainBanner_img_750.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("mainBanner_img_751.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("mainBanner_img_752.jpg") %>
    </div>
  </div>
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>캠페인명</th>
      <th>클라이언트</th>
      <th>이메일</th>
      <th>시작</th>
      <th>종료</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= link_to campaign.id, campaign_path(campaign) %></td>
        <td><%= campaign.name %></td>
        <td><%= campaign.client.name if campaign.client %></td>
        <td><%= campaign.client.email if campaign.client %></td>
        <td><%= campaign.start_date %></td>
        <td><%= campaign.end_date %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_campaign_path(campaign), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      campaign_path(campaign),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if client_signed_in? %>
	<%= link_to t('.new', :default => t("helpers.links.new")),
	            new_campaign_path,
	            :class => 'btn btn-primary' %>
<% end %>

app/views/campaigns/new.html.erb
<div class="page-header">
  <h1>새로운 캠페인 등록</h1>
</div>

<div style='padding-bottom:15px'>
  <h4>캠페인 제목과 기간을 입력해주세요.</h4>
</div>

<%= render :partial => 'new_form' %>

app/views/campaigns/show.html.erb
<%- model_class = Campaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @campaign.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @campaign.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_date) %>:</strong></dt>
  <dd><%= @campaign.end_date %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              campaigns_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_campaign_path(@campaign), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              campaign_path(@campaign),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/clients/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "다솔인" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <link href="/assets/favicon.ico" rel="shortcut icon" >

    <!-- Google Fonts 
    <link href="http://fonts.googleapis.com/css?family=Enriqueta:400,700" rel="stylesheet" type="text/css" >
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700" rel="stylesheet" type="text/css" >
    -->

  </head>
  <body>
    <div id="fb-root"></div>

    <%= nav_bar :fixed => :top, :brand => "다솔인" do %>
      <%= menu_group :pull => :right do %>
        <% if user_signed_in? %>
          <%= drop_down current_user.email do %>
            <%= menu_item "마이페이지", '#' %>
            <%= drop_down_divider %>
            <%= menu_item "로그아웃", destroy_user_session_path, :method => :delete %>
          <% end %>
        <% elsif client_signed_in? %> 
          <%= menu_item "클라이언트 모드", '#' %> 
          <%= menu_divider %>
          <%= drop_down current_client.email do %>
            <%= menu_item "마이페이지", '#' %>
            <%= drop_down_divider %>
            <%= menu_item "로그아웃", destroy_client_session_path, :method => :delete %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

    <div class="container">
      <div class="row">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <hr />

      <footer>
        <p>&copy; Dasolin Company 2013</p>
      </footer>

      <!--
      <%= debug(params) if Rails.env.development? %>
      -->

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <script>
      (function(d,s,id){
        var fb_appid="144880112370835";
        var js,fjs=d.getElementsByTagName(s)[0];
        if(d.getElementById(id)) return;
        js=d.createElement(s); js.id=id;
        js.src="//connect.facebook.net/ko_KR/all.js#xfbml=1&appId="+fb_appid;
        fjs.parentNode.insertBefore(js,fjs);
      }(document,'script','facebook-jssdk'));
    </script>

  </body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<style>
  img.displayed { 
    display: block;
    margin-left: auto;
    margin-right: auto
  }
</style>
<img class="displayed" src="/assets/sqspc2-1.jpg" width=640 />

<hr />

<style>
  #login_or_register {
    text-align:center;
  }
</style>
<div id="login_or_register">
  <%= link_to "블로거 로그인", new_user_session_path %> |
  <%= link_to "블로거 등록", new_user_registration_path %> |
  <%= link_to "클라이언트 로그인", new_client_session_path %> |
  <%= link_to "클라이언트 등록", new_client_registration_path %>
</div>

<!--
<div class="fb-like"  data-send="true" data-width="450" data-show-faces="true"></div>
-->